version: '3.9'

services:
  graph:
    build:
      context: .
    container_name: reactograph
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
      - './data:/app/data'
    environment:
      - REACT_APP_DATA_API=${REACT_APP_DATA_API} #/data/d.json
