version: '3.9'

services:
  graph:
    build:
      context: .
    container_name: reactograph
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
      - './data:/app/data'
    environment:
      - REACT_APP_DATA_API=${REACT_APP_DATA_API} #/data/d.json
      - REACT_APP_HOST=${REACT_APP_HOST}
      - REACT_APP_DEFAULT_TERM=${REACT_APP_DEFAULT_TERM}
      - "REACT_APP_DATASET_URL"
      - "REACT_APP_LOGIN_TEXT"
      - "REACT_APP_LOGGED_IN_TEXT"
      - "REACT_APP_OAUTH_RESPONSE_TYPE"
      - "REACT_APP_OAUTH_SCOPE"
      - "REACT_APP_OAUTH_PROMPT"
    networks:
      - default
      - traefik
networks:
  traefik:
    external: true
